In [1]:
# import libraries
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('mode.use_inf_as_na', True)

In [2]:
# load in raw dataset
df_raw =  pd.read_csv("SO_ML_2022.csv", skiprows=1)
df_raw.head()

,fractional_year,O7_O6_ratio,C6_C4_ratio,C6_C5_ratio,Fe_O_ratio,O_ave_charge,velocity,density
0,2022.049316,0.089865,2.458390,0.444265,0.150213,6.074951,494.797,2.82344
1,2022.049335,0.083158,2.841864,0.410422,0.160867,6.072842,489.727,2.96590
2,2022.049354,0.098469,2.527932,0.328493,0.132257,6.086165,491.465,2.65348
3,2022.049373,0.070984,2.794871,0.356665,0.135882,6.060820,490.259,2.89073
4,2022.049392,0.078036,1.416381,0.329367,0.154701,6.068972,493.497,2.96546

In [3]:
df_raw.describe()

,fractional_year,O7_O6_ratio,C6_C4_ratio,C6_C5_ratio,Fe_O_ratio,O_ave_charge,velocity,density
count,23148.000000,2.314800e+04,2.314800e+04,2.314800e+04,2.314800e+04,2.314800e+04,23096.00000,23148.000000
mean,2022.544265,-1.304216e+30,-1.304216e+30,-1.304216e+30,-1.304216e+30,-1.304216e+30,461.93650,20.353228
std,0.300886,3.367740e+30,3.367740e+30,3.367740e+30,3.367740e+30,3.367740e+30,123.71209,25.163787
min,2022.049316,-1.000000e+31,-1.000000e+31,-1.000000e+31,-1.000000e+31,-1.000000e+31,213.68700,0.075644
25%,2022.283772,5.182862e-02,1.346901e+00,2.926058e-01,1.010134e-01,6.038909e+00,369.10025,7.562115
50%,2022.644112,1.092680e-01,2.868476e+00,4.480552e-01,1.355404e-01,6.101439e+00,443.34450,12.452700
75%,2022.807810,2.039887e-01,5.684307e+00,6.523078e-01,1.775669e-01,6.194446e+00,534.45150,23.924950
max,2022.999977,2.588494e+00,1.249720e+02,1.209064e+01,8.980139e+00,7.323942e+00,1135.32000,271.159000

In [4]:
df_raw.isnull().sum()

fractional_year     0
O7_O6_ratio         0
C6_C4_ratio         0
C6_C5_ratio         0
Fe_O_ratio          0
O_ave_charge        0
velocity           52
density             0
dtype: int64

- missing velocity numbers were inf convertered to nan so they could be dropped later

## Clean Dataset

- O7_O6_ratio: ratio of Oxygen atoms with 7 missing elections (+7) and Oxygen atoms with 6 missing electrons (+6)
    - ratio cannot be negative so need to remove rows where this is negative

- C6_C4_ratio: ratio of +6 carbon to +4 carbon
    - ratio cannot be negative

- C6_C5_ratio: ratio of +6 carbon to +5 carbon
    - ratio cannot be negative

- Fe_O_ratio: Ratio of iron to oxygen
    - ratio cannot be negative

- O_ave_charge: average charge of oxygen atoms
    - cannot be over 8 because oxygen only has 8 electrons to lose

- velocity: velocity of particles in solar wind
    - should be around a few hundred, need to remove higher or lower

- density: particle density of solar wind
    - should be from 0-a few hundred

In [5]:
# remove rows with negative ratios
df = df_raw[df_raw['O7_O6_ratio'] >= 0]
df = df[df['C6_C4_ratio'] >= 0]
df = df[df['C6_C5_ratio'] >= 0]
df = df[df['Fe_O_ratio'] >= 0]

In [6]:
# remove rows where O_ave_charge is greater than 8
df = df[df['O_ave_charge'] < 8]

In [7]:
# remove rows with nan as a velocity
df.dropna(inplace=True)

In [8]:
df.describe()

,fractional_year,O7_O6_ratio,C6_C4_ratio,C6_C5_ratio,Fe_O_ratio,O_ave_charge,velocity,density
count,20077.000000,20077.000000,20077.000000,20077.000000,20077.000000,20077.000000,20077.000000,20077.000000
mean,2022.529927,0.173934,5.126117,0.580191,0.166790,6.159022,435.607255,21.430696
std,0.305104,0.155615,5.837108,0.365408,0.133891,0.141912,91.826304,25.484307
min,2022.049316,0.012432,0.149342,0.058647,0.020420,5.907891,231.300000,0.959811
25%,2022.267363,0.070190,1.883380,0.351437,0.115890,6.058576,364.083000,8.138440
50%,2022.473065,0.130636,3.404758,0.490620,0.144544,6.124208,423.379000,13.041500
75%,2022.810108,0.222039,6.263270,0.694863,0.186586,6.211381,507.403000,25.465300
max,2022.999977,2.588494,124.971985,12.090635,8.980139,7.323942,803.652000,271.159000

In [9]:
df.head()

,fractional_year,O7_O6_ratio,C6_C4_ratio,C6_C5_ratio,Fe_O_ratio,O_ave_charge,velocity,density
0,2022.049316,0.089865,2.458390,0.444265,0.150213,6.074951,494.797,2.82344
1,2022.049335,0.083158,2.841864,0.410422,0.160867,6.072842,489.727,2.96590
2,2022.049354,0.098469,2.527932,0.328493,0.132257,6.086165,491.465,2.65348
3,2022.049373,0.070984,2.794871,0.356665,0.135882,6.060820,490.259,2.89073
4,2022.049392,0.078036,1.416381,0.329367,0.154701,6.068972,493.497,2.96546

In [19]:
# save cleaned file as csv
df.to_csv('SO_ML_2022_cleaned.csv')